version: '3.4'

services:
  todo-api:
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  todo-db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: UltimateSecretPasswordForDb
      
  todo-api-documentation:
    ports:
      - "8081:80"