version: '3.4'

networks:
  to-do-network:

services:
  to-do-api:
    container_name: to-do-api
    image: ${DOCKER_REGISTRY-}to-do-api
    build:
      context: .
      dockerfile: ToDo.API/Dockerfile
    restart: always
    depends_on:
      - to-do-db
    networks:
      - to-do-network

  to-do-db:
    container_name: to-do-db
    image: postgres
    restart: always
    networks:
      - to-do-network

  to-do-api-documentation:
    container_name: to-do-api-documentation
    image: ${DOCKER_REGISTRY-}to-do-api-documentation
    build:
      context: .
      dockerfile: ToDo.API.Documentation/Dockerfile
    restart: always
    networks:
      - to-do-network