version: '3.4'

networks:
  todo-network:

services:
  todo-api:
    container_name: todo-api
    image: ${DOCKER_REGISTRY-}todo-api
    build:
      context: .
      dockerfile: ToDo.API/Dockerfile
    restart: always
    depends_on:
      - todo-db
    ports:
      - "8080:80"
    networks:
      - todo-network

  todo-db:
    container_name: todo-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: UltimateSecretPasswordForDb
    ports:
      - "5432:5432"
    networks:
      - todo-network

  todo-api-documentation:
    container_name: todo-api-documentation
    image: ${DOCKER_REGISTRY-}todo-api-documentation
    build:
      context: .
      dockerfile: ToDo.API.Documentation/Dockerfile
    restart: always
    ports:
      - "8081:80"