name: Run Tests

on: 
  push:
    branches:
      - '**'
  
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ToDo.sln
      
    - name: Build
      run: dotnet build ToDo.sln --no-restore
      
    - name: Test
      run: dotnet test ToDo.sln --no-build --verbosity normal
